"""empty message

Revision ID: 8eacdca4ca7a
Revises: bd60fe7f010a
Create Date: 2018-08-22 21:47:05.282987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eacdca4ca7a'
down_revision = 'bd60fe7f010a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('house',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('house_week_new_value', sa.String(length=100), nullable=False),
    sa.Column('house_week_old_value', sa.String(length=100), nullable=False),
    sa.Column('house_yestoday_trans_num', sa.String(length=100), nullable=False),
    sa.Column('house_yestoday_trans_price', sa.String(length=100), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('img', sa.String(length=100), nullable=False),
    sa.Column('link', sa.String(length=100), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('weather', sa.String(length=100), nullable=False),
    sa.Column('weather_other', sa.String(length=100), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    op.drop_table('news')
    op.drop_table('house')
    # ### end Alembic commands ###
