"""empty message

Revision ID: bd60fe7f010a
Revises: 853dc242a938
Create Date: 2018-08-22 11:06:33.243447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd60fe7f010a'
down_revision = '853dc242a938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('current_date', sa.DateTime(), nullable=True))
    op.drop_column('banner', 'link_url')
    op.drop_column('banner', 'priority')
    op.drop_column('banner', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('banner', sa.Column('priority', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('banner', sa.Column('link_url', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('banner', 'current_date')
    # ### end Alembic commands ###
