"""empty message

Revision ID: c7c115127d45
Revises: d5e5bbe29ce5
Create Date: 2018-08-28 10:55:17.019910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7c115127d45'
down_revision = 'd5e5bbe29ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('banner', 'extra_arg',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    op.drop_column('house', 'extra_arg')
    op.drop_column('news', 'extra_arg')
    op.drop_column('weather', 'extra_arg')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('extra_arg', mysql.VARCHAR(length=500), nullable=False))
    op.add_column('news', sa.Column('extra_arg', mysql.VARCHAR(length=500), nullable=False))
    op.add_column('house', sa.Column('extra_arg', mysql.VARCHAR(length=500), nullable=False))
    op.alter_column('banner', 'extra_arg',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
