"""empty message

Revision ID: d5e5bbe29ce5
Revises: d1cb570314a0
Create Date: 2018-08-28 10:47:26.670217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e5bbe29ce5'
down_revision = 'd1cb570314a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('extra_arg', sa.String(length=500), nullable=False))
    op.add_column('house', sa.Column('extra_arg', sa.String(length=500), nullable=False))
    op.add_column('news', sa.Column('extra_arg', sa.String(length=500), nullable=False))
    op.add_column('weather', sa.Column('extra_arg', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather', 'extra_arg')
    op.drop_column('news', 'extra_arg')
    op.drop_column('house', 'extra_arg')
    op.drop_column('banner', 'extra_arg')
    # ### end Alembic commands ###
