"""empty message

Revision ID: ff12276c797c
Revises: c7c115127d45
Create Date: 2018-08-28 11:33:09.683738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff12276c797c'
down_revision = 'c7c115127d45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('current_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather', 'current_date')
    # ### end Alembic commands ###
